### ISSUE TITLE
后端API问题

### ISSUE THREAD

**Issue by tovarsh** [LuYou-fangweng/genshin-web#1]
作者你好, 你的api服务没用了, 可否开放服务或者sql

**Comment by LuYou-fangweng** [comment]
您好，关于开放服务，对此我只能感到非常抱歉，事实上api服务不但没了，服务器都已经释放了，而我也没有重新部署的想法与精力，所以没办法开放服务了，非常抱歉。
如果不是您给我发个评论，我可能都记不起我还做了个仿原神游戏官网这个网站，总之，祝您生活愉快

**Comment by LuYou-fangweng** [comment]
> 作者你好, 你的api服务没用了, 可否开放服务或者sql

您好，关于开放服务，对此我只能感到非常抱歉，事实上api服务不但没了，服务器都已经释放了，而我也没有重新部署的想法与精力，所以没办法开放服务了，非常抱歉。
如果不是您给我发个评论，我可能都记不起我还做了个仿原神游戏官网这个网站，总之，祝您生活愉快

**Comment by tovarsh** [comment]
> > 作者你好, 你的api服务没用了, 可否开放服务或者sql
> 
> 您好，关于开放服务，对此我只能感到非常抱歉，事实上api服务不但没了，服务器都已经释放了，而我也没有重新部署的想法与精力，所以没办法开放服务了，非常抱歉。
> 如果不是您给我发个评论，我可能都记不起我还做了个仿原神游戏官网这个网站，总之，祝您生活愉快

感谢作者百忙之中抽空回复。我们生产实习刚好用到，作者项目让我不用重复造轮子，已经很感谢了。祝您工作顺利
